"""One-page, print-ready kitchen production sheet (self-contained HTML: open it and print, or save as PDF)."""
from __future__ import annotations

import html

from product import core

e = lambda x: html.escape(str(x))  # noqa: E731


def plan_from_trace(trace: dict, standing: dict) -> tuple[dict, dict]:
    plan = trace["action"].get("final_plan_kg") or standing
    usable = (trace.get("details") or {}).get("usable_carry_over_kg") or {}
    return {g: float(plan[g]) for g in core.GROUPS}, {g: float(usable.get(g, 0.0)) for g in core.GROUPS}


def build(hotel: str, service: str, date: str, plan: dict, usable: dict, standing: dict, decisions: list[dict],
          approver: str = "", autonomy: str = "", carry_items: list | None = None, transfers: list | None = None,
          note: str = "") -> str:
    standing = {g: float(standing[g]) for g in core.GROUPS}
    plan = {g: float(plan[g]) for g in core.GROUPS}
    rows = "".join(
        f"<tr><td>{e(core.GROUP_LABEL[g])}</td><td class='n big'>{plan[g]:.1f}</td><td class='n'>{usable.get(g, 0):.1f}</td>"
        f"<td class='n'>{standing[g]:.1f}</td><td class='n'>{(plan[g] / standing[g] - 1) if standing[g] else 0:+.1%}</td>"
        f"<td class='box'></td><td class='box'></td></tr>" for g in core.GROUPS)
    total = sum(plan.values())
    use_first = "".join(f"<li><b>{e(r['item'])}</b> · {float(r['kg']):.1f} kg</li>" for r in (carry_items or [])
                        if r.get("kg") and r.get("within_shelf_life", True))
    moves = "".join(f"<li>{e(t)}</li>" for t in (transfers or []))
    decs = "".join(f"<tr><td>{e(d['id'])}</td><td>{e(d['what'])}</td><td>{e(d['who'])}</td><td>{e(d['status'])}</td></tr>"
                   for d in decisions)
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>Kitchen sheet {e(date)} · {e(hotel)}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
@page {{ size: A4; margin: 14mm; }}
body {{ font-family: Inter, 'Helvetica Neue', Arial, sans-serif; color: #17211C; margin: 24px; }}
.top {{ display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 3px solid #1F3A2F; padding-bottom: 10px; }}
h1 {{ margin: 0; font-size: 26px; color: #1F3A2F; }} .k {{ font-size: 11px; letter-spacing: .14em; text-transform: uppercase; color: #8a6d3b; font-weight: 700; }}
.meta {{ text-align: right; font-size: 13px; color: #4b5650; line-height: 1.5; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 14px; }}
th {{ text-align: left; font-size: 11px; letter-spacing: .08em; text-transform: uppercase; color: #5F6B63; border-bottom: 2px solid #1F3A2F; padding: 8px 6px; }}
td {{ border-bottom: 1px solid #E3E6E0; padding: 10px 6px; }} .n {{ text-align: right; font-variant-numeric: tabular-nums; }}
.big {{ font-size: 20px; font-weight: 800; color: #1F3A2F; }} .box {{ width: 70px; border-left: 1px dashed #CBD3CC; }}
h2 {{ font-size: 14px; margin: 22px 0 6px; color: #1F3A2F; }} ul {{ margin: 0; padding-left: 18px; font-size: 13px; line-height: 1.6; }}
.dec td {{ font-size: 12px; padding: 6px; }} .dec td:first-child {{ white-space: nowrap; font-weight: 700; }} .sign {{ display: flex; gap: 40px; margin-top: 30px; font-size: 12px; color: #5F6B63; }}
.sign div {{ flex: 1; border-top: 1px solid #17211C; padding-top: 6px; }}
.foot {{ margin-top: 18px; font-size: 10px; color: #8a948d; }}
.btn {{ display: inline-block; margin: 0 0 16px; padding: 8px 14px; background: #1F3A2F; color: #fff; border-radius: 8px; text-decoration: none; font-size: 13px; }}
@media print {{ .btn {{ display: none; }} body {{ margin: 0; }} }}
</style></head><body>
<a class="btn" href="#" onclick="window.print();return false;">Print this sheet</a>
<div class="top"><div><div class="k">Kitchen production sheet</div><h1>{e(service)} · {e(date)}</h1></div>
<div class="meta"><b>{e(hotel)}</b><br>Approved by {e(approver or '—')}<br>Autonomy: {e(autonomy or '—')}</div></div>
<table><thead><tr><th>Item group</th><th class="n">Prepare (kg)</th><th class="n">Use carry-over first (kg)</th>
<th class="n">Standing par (kg)</th><th class="n">vs par</th><th>Prepared ✓</th><th>Left over (kg)</th></tr></thead>
<tbody>{rows}<tr><td><b>Total</b></td><td class="n big">{total:.1f}</td><td></td><td class="n">{sum(standing.values()):.1f}</td>
<td></td><td></td><td></td></tr></tbody></table>
{f"<h2>Use first (carry-over within shelf life)</h2><ul>{use_first}</ul>" if use_first else ""}
{f"<h2>Move to another outlet</h2><ul>{moves}</ul>" if moves else ""}
<h2>Decisions behind this plan</h2><table class="dec"><thead><tr><th>ID</th><th>Decision</th><th>Human decision</th><th>Status</th></tr></thead>
<tbody>{decs}</tbody></table>
<div class="sign"><div>Chef</div><div>F&amp;B Manager</div><div>Time</div></div>
<div class="foot">Generated by Hotel AgentOps · governed AI for food production{(' · ' + e(note)) if note else ''}. Record the "Left over" column at the
end of service and enter it in Close out service.</div>
</body></html>"""
